use extension_protocol::ddl::{
    BuildAlterTableParams, BuildAlterTableResult, BuildCreateTableParams, BuildCreateTableResult,
    BuildDdlParams, BuildDdlResult, BuildDropParams, BuildDropResult, ColumnSpec, DdlBuildOp,
    TableSpec,
};
use extension_protocol::error::ProtocolError;
use extension_protocol::schema::ObjectKind;
use serde_json::Value;

use crate::server::{invalid_params, params_deserialize_error};

pub fn handle_ddl_build(params: &Value) -> Result<Value, ProtocolError> {
    let p: BuildDdlParams =
        serde_json::from_value(params.clone()).map_err(params_deserialize_error)?;
    let result = match p.op {
        DdlBuildOp::CreateTable => {
            let spec: TableSpec =
                serde_json::from_value(p.payload).map_err(params_deserialize_error)?;
            BuildDdlResult {
                statements: build_create_timeseries_statements(&spec, false),
                warnings: ddl_warnings(&spec),
            }
        }
        DdlBuildOp::ColumnDefinition => {
            let column: ColumnSpec =
                serde_json::from_value(p.payload).map_err(params_deserialize_error)?;
            BuildDdlResult {
                statements: vec![build_column_definition(&column)],
                warnings: Vec::new(),
            }
        }
        DdlBuildOp::DropTable => {
            let drop: BuildDropParams =
                serde_json::from_value(p.payload).map_err(params_deserialize_error)?;
            BuildDdlResult {
                statements: vec![build_drop_sql(&drop)?],
                warnings: Vec::new(),
            }
        }
        other => {
            return Err(invalid_params(format!(
                "IoTDB DDL builder does not support generic op `{other:?}`"
            )));
        }
    };
    serde_json::to_value(result).map_err(params_deserialize_error)
}

pub fn handle_ddl_build_create_table(params: &Value) -> Result<Value, ProtocolError> {
    let p: BuildCreateTableParams =
        serde_json::from_value(params.clone()).map_err(params_deserialize_error)?;
    let statements = build_create_timeseries_statements(&p.spec, p.options.if_not_exists);
    let result = BuildCreateTableResult {
        sql: statements.join(";\n"),
        statements,
    };
    serde_json::to_value(result).map_err(params_deserialize_error)
}

pub fn handle_ddl_build_alter_table(params: &Value) -> Result<Value, ProtocolError> {
    let p: BuildAlterTableParams =
        serde_json::from_value(params.clone()).map_err(params_deserialize_error)?;
    let from_names = p
        .from_spec
        .columns
        .iter()
        .map(|column| column.name.as_str())
        .collect::<std::collections::BTreeSet<_>>();
    let added = p
        .to_spec
        .columns
        .iter()
        .filter(|column| !from_names.contains(column.name.as_str()))
        .map(|column| build_create_timeseries(&p.to_spec.name, column, false))
        .collect::<Vec<_>>();
    let mut warnings = Vec::new();
    if !p.column_renames.is_empty() {
        warnings.push("IoTDB does not support renaming timeseries through this builder".into());
    }
    if p.from_spec.columns.len() > p.to_spec.columns.len() {
        warnings
            .push("IoTDB destructive timeseries drops are not generated by alter builder".into());
    }
    let result = BuildAlterTableResult {
        statements: added,
        rollback_statements: Vec::new(),
        warnings,
    };
    serde_json::to_value(result).map_err(params_deserialize_error)
}

pub fn handle_ddl_build_drop(params: &Value) -> Result<Value, ProtocolError> {
    let p: BuildDropParams =
        serde_json::from_value(params.clone()).map_err(params_deserialize_error)?;
    serde_json::to_value(BuildDropResult {
        sql: build_drop_sql(&p)?,
    })
    .map_err(params_deserialize_error)
}

fn build_create_timeseries_statements(spec: &TableSpec, if_not_exists: bool) -> Vec<String> {
    spec.columns
        .iter()
        .filter(|column| !column.name.eq_ignore_ascii_case("time"))
        .map(|column| build_create_timeseries(&spec.name, column, if_not_exists))
        .collect()
}

fn build_create_timeseries(device: &str, column: &ColumnSpec, if_not_exists: bool) -> String {
    let if_not_exists = if if_not_exists { " IF NOT EXISTS" } else { "" };
    format!(
        "CREATE TIMESERIES{if_not_exists} {}.{} WITH DATATYPE={}, ENCODING=PLAIN, COMPRESSOR=SNAPPY",
        device,
        column.name,
        iotdb_type(&column.type_str)
    )
}

fn build_column_definition(column: &ColumnSpec) -> String {
    format!(
        "{} WITH DATATYPE={}, ENCODING=PLAIN, COMPRESSOR=SNAPPY",
        column.name,
        iotdb_type(&column.type_str)
    )
}

fn build_drop_sql(p: &BuildDropParams) -> Result<String, ProtocolError> {
    match p.kind {
        ObjectKind::Table => Ok(format!("DELETE TIMESERIES {}.**", p.name)),
        ObjectKind::View => Err(invalid_params("IoTDB does not support DROP VIEW")),
        _ => Err(invalid_params(format!(
            "IoTDB DDL builder does not support dropping `{}`",
            p.kind.as_str()
        ))),
    }
}

fn ddl_warnings(spec: &TableSpec) -> Vec<String> {
    let mut warnings = Vec::new();
    if spec
        .columns
        .iter()
        .any(|column| column.name.eq_ignore_ascii_case("time"))
    {
        warnings.push(
            "IoTDB timestamp column is implicit; `Time` is not created as a timeseries".into(),
        );
    }
    warnings
}

fn iotdb_type(type_str: &str) -> &'static str {
    let normalized = type_str.trim().to_ascii_uppercase();
    match normalized.as_str() {
        "BOOL" | "BOOLEAN" => "BOOLEAN",
        "INT" | "INTEGER" | "INT32" => "INT32",
        "BIGINT" | "INT64" | "LONG" => "INT64",
        "FLOAT" | "REAL" => "FLOAT",
        "DOUBLE" | "FLOAT64" => "DOUBLE",
        "TEXT" | "STRING" | "VARCHAR" | "CHAR" => "TEXT",
        _ => "TEXT",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use extension_protocol::ddl::{
        BuildCreateTableParams, BuildDropParams, ColumnSpec, CreateTableOptions, TableSpec,
    };

    #[test]
    fn build_create_table_generates_timeseries_per_non_time_column() {
        let result = handle_ddl_build_create_table(
            &serde_json::to_value(BuildCreateTableParams {
                conn_id: None,
                spec: TableSpec {
                    name: "root.ln.wf01.wt01".into(),
                    columns: vec![
                        ColumnSpec {
                            name: "Time".into(),
                            type_str: "INT64".into(),
                            nullable: false,
                            ..Default::default()
                        },
                        ColumnSpec {
                            name: "temperature".into(),
                            type_str: "FLOAT".into(),
                            ..Default::default()
                        },
                        ColumnSpec {
                            name: "status".into(),
                            type_str: "BOOLEAN".into(),
                            ..Default::default()
                        },
                    ],
                    ..Default::default()
                },
                options: CreateTableOptions {
                    if_not_exists: true,
                    ..Default::default()
                },
            })
            .unwrap(),
        )
        .unwrap();

        assert_eq!(result["statements"].as_array().unwrap().len(), 2);
        assert!(result["sql"].as_str().unwrap().contains(
            "CREATE TIMESERIES IF NOT EXISTS root.ln.wf01.wt01.temperature WITH DATATYPE=FLOAT"
        ));
    }

    #[test]
    fn build_drop_table_deletes_device_timeseries() {
        let result = handle_ddl_build_drop(
            &serde_json::to_value(BuildDropParams {
                kind: ObjectKind::Table,
                name: "root.ln.wf01.wt01".into(),
                schema: None,
                database: None,
                if_exists: true,
                cascade: true,
            })
            .unwrap(),
        )
        .unwrap();

        assert_eq!(result["sql"], "DELETE TIMESERIES root.ln.wf01.wt01.**");
    }
}
