[package]
name = "docker-provider"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
bollard = { workspace = true }
extension-protocol = { workspace = true }
futures-util = { workspace = true }
interprocess = { workspace = true }
libc = "0.2"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
uuid = { workspace = true }

[dev-dependencies]
extension-host = { workspace = true }
tempfile = "3"
