pub struct DuckDbBuiltinFunction {
    pub name: &'static str,
    pub signature: &'static str,
    pub kind: &'static str,
    pub return_type: Option<&'static str>,
    pub description: &'static str,
}

pub const DUCKDB_BUILTIN_FUNCTIONS: &[DuckDbBuiltinFunction] = &[
    DuckDbBuiltinFunction {
        name: "abs",
        signature: "abs(x)",
        kind: "scalar",
        return_type: None,
        description: "Absolute value",
    },
    DuckDbBuiltinFunction {
        name: "acos",
        signature: "acos(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Arccosine",
    },
    DuckDbBuiltinFunction {
        name: "acosh",
        signature: "acosh(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Inverse hyperbolic cosine",
    },
    DuckDbBuiltinFunction {
        name: "age",
        signature: "age(timestamp[, timestamp])",
        kind: "scalar",
        return_type: Some("INTERVAL"),
        description: "Difference between timestamps",
    },
    DuckDbBuiltinFunction {
        name: "alias",
        signature: "alias(expr)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Name of an expression",
    },
    DuckDbBuiltinFunction {
        name: "any_value",
        signature: "any_value(arg)",
        kind: "aggregate",
        return_type: None,
        description: "First non-NULL value",
    },
    DuckDbBuiltinFunction {
        name: "approx_count_distinct",
        signature: "approx_count_distinct(any)",
        kind: "aggregate",
        return_type: Some("BIGINT"),
        description: "Approximate distinct count using HyperLogLog",
    },
    DuckDbBuiltinFunction {
        name: "approx_quantile",
        signature: "approx_quantile(x, pos)",
        kind: "aggregate",
        return_type: None,
        description: "Approximate quantile using T-Digest",
    },
    DuckDbBuiltinFunction {
        name: "arbitrary",
        signature: "arbitrary(arg)",
        kind: "aggregate",
        return_type: None,
        description: "First value including NULLs",
    },
    DuckDbBuiltinFunction {
        name: "arg_max",
        signature: "arg_max(arg, val)",
        kind: "aggregate",
        return_type: None,
        description: "arg value at maximum val",
    },
    DuckDbBuiltinFunction {
        name: "arg_min",
        signature: "arg_min(arg, val)",
        kind: "aggregate",
        return_type: None,
        description: "arg value at minimum val",
    },
    DuckDbBuiltinFunction {
        name: "array_agg",
        signature: "array_agg(arg)",
        kind: "aggregate",
        return_type: Some("LIST"),
        description: "Collect values into a list",
    },
    DuckDbBuiltinFunction {
        name: "ascii",
        signature: "ascii(string)",
        kind: "scalar",
        return_type: Some("INTEGER"),
        description: "Unicode codepoint of first character",
    },
    DuckDbBuiltinFunction {
        name: "asin",
        signature: "asin(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Arcsine",
    },
    DuckDbBuiltinFunction {
        name: "asinh",
        signature: "asinh(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Inverse hyperbolic sine",
    },
    DuckDbBuiltinFunction {
        name: "atan",
        signature: "atan(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Arctangent",
    },
    DuckDbBuiltinFunction {
        name: "atan2",
        signature: "atan2(y, x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Two-argument arctangent",
    },
    DuckDbBuiltinFunction {
        name: "atanh",
        signature: "atanh(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Inverse hyperbolic tangent",
    },
    DuckDbBuiltinFunction {
        name: "avg",
        signature: "avg(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Average value",
    },
    DuckDbBuiltinFunction {
        name: "bar",
        signature: "bar(x, min, max, width)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Draw a horizontal bar",
    },
    DuckDbBuiltinFunction {
        name: "base64",
        signature: "base64(blob)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Base64 encode a blob",
    },
    DuckDbBuiltinFunction {
        name: "bit_and",
        signature: "bit_and(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Bitwise AND aggregate",
    },
    DuckDbBuiltinFunction {
        name: "bit_count",
        signature: "bit_count(x)",
        kind: "scalar",
        return_type: Some("INTEGER"),
        description: "Count set bits",
    },
    DuckDbBuiltinFunction {
        name: "bit_length",
        signature: "bit_length(string)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Length in bits",
    },
    DuckDbBuiltinFunction {
        name: "bit_or",
        signature: "bit_or(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Bitwise OR aggregate",
    },
    DuckDbBuiltinFunction {
        name: "bit_xor",
        signature: "bit_xor(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Bitwise XOR aggregate",
    },
    DuckDbBuiltinFunction {
        name: "bool_and",
        signature: "bool_and(arg)",
        kind: "aggregate",
        return_type: Some("BOOLEAN"),
        description: "True if all inputs are true",
    },
    DuckDbBuiltinFunction {
        name: "bool_or",
        signature: "bool_or(arg)",
        kind: "aggregate",
        return_type: Some("BOOLEAN"),
        description: "True if any input is true",
    },
    DuckDbBuiltinFunction {
        name: "ceil",
        signature: "ceil(x)",
        kind: "scalar",
        return_type: None,
        description: "Round up",
    },
    DuckDbBuiltinFunction {
        name: "ceiling",
        signature: "ceiling(x)",
        kind: "scalar",
        return_type: None,
        description: "Round up",
    },
    DuckDbBuiltinFunction {
        name: "century",
        signature: "century(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract century",
    },
    DuckDbBuiltinFunction {
        name: "chr",
        signature: "chr(codepoint)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Character from codepoint",
    },
    DuckDbBuiltinFunction {
        name: "coalesce",
        signature: "coalesce(val1, val2, ...)",
        kind: "scalar",
        return_type: None,
        description: "First non-NULL value",
    },
    DuckDbBuiltinFunction {
        name: "concat",
        signature: "concat(arg1, arg2, ...)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Concatenate values",
    },
    DuckDbBuiltinFunction {
        name: "concat_ws",
        signature: "concat_ws(separator, arg1, arg2, ...)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Concatenate with separator",
    },
    DuckDbBuiltinFunction {
        name: "contains",
        signature: "contains(string, search_string)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether string contains search string",
    },
    DuckDbBuiltinFunction {
        name: "corr",
        signature: "corr(y, x)",
        kind: "aggregate",
        return_type: Some("DOUBLE"),
        description: "Correlation coefficient",
    },
    DuckDbBuiltinFunction {
        name: "cos",
        signature: "cos(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Cosine",
    },
    DuckDbBuiltinFunction {
        name: "cosh",
        signature: "cosh(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Hyperbolic cosine",
    },
    DuckDbBuiltinFunction {
        name: "cot",
        signature: "cot(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Cotangent",
    },
    DuckDbBuiltinFunction {
        name: "count",
        signature: "count([arg])",
        kind: "aggregate",
        return_type: Some("BIGINT"),
        description: "Count rows or values",
    },
    DuckDbBuiltinFunction {
        name: "count_if",
        signature: "count_if(condition)",
        kind: "aggregate",
        return_type: Some("BIGINT"),
        description: "Count true values",
    },
    DuckDbBuiltinFunction {
        name: "current_catalog",
        signature: "current_catalog",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Current catalog",
    },
    DuckDbBuiltinFunction {
        name: "current_database",
        signature: "current_database()",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Current database/catalog",
    },
    DuckDbBuiltinFunction {
        name: "current_date",
        signature: "current_date",
        kind: "scalar",
        return_type: Some("DATE"),
        description: "Current date",
    },
    DuckDbBuiltinFunction {
        name: "current_localtime",
        signature: "current_localtime()",
        kind: "scalar",
        return_type: Some("TIME"),
        description: "Current local time",
    },
    DuckDbBuiltinFunction {
        name: "current_localtimestamp",
        signature: "current_localtimestamp()",
        kind: "scalar",
        return_type: Some("TIMESTAMP"),
        description: "Current local timestamp",
    },
    DuckDbBuiltinFunction {
        name: "current_query",
        signature: "current_query()",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Current query text",
    },
    DuckDbBuiltinFunction {
        name: "current_schema",
        signature: "current_schema()",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Current schema",
    },
    DuckDbBuiltinFunction {
        name: "current_schemas",
        signature: "current_schemas(boolean)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Current schemas",
    },
    DuckDbBuiltinFunction {
        name: "current_setting",
        signature: "current_setting(name)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Current setting value",
    },
    DuckDbBuiltinFunction {
        name: "current_timestamp",
        signature: "current_timestamp",
        kind: "scalar",
        return_type: Some("TIMESTAMP WITH TIME ZONE"),
        description: "Current timestamp",
    },
    DuckDbBuiltinFunction {
        name: "current_user",
        signature: "current_user",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Current user",
    },
    DuckDbBuiltinFunction {
        name: "date_diff",
        signature: "date_diff(part, startdate, enddate)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Boundary count between dates",
    },
    DuckDbBuiltinFunction {
        name: "date_part",
        signature: "date_part(part, date)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract date part",
    },
    DuckDbBuiltinFunction {
        name: "date_sub",
        signature: "date_sub(part, startdate, enddate)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Signed interval difference",
    },
    DuckDbBuiltinFunction {
        name: "date_trunc",
        signature: "date_trunc(part, date)",
        kind: "scalar",
        return_type: None,
        description: "Truncate date/time to part",
    },
    DuckDbBuiltinFunction {
        name: "day",
        signature: "day(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract day",
    },
    DuckDbBuiltinFunction {
        name: "dayname",
        signature: "dayname(date)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Day name",
    },
    DuckDbBuiltinFunction {
        name: "dayofmonth",
        signature: "dayofmonth(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract day of month",
    },
    DuckDbBuiltinFunction {
        name: "dayofweek",
        signature: "dayofweek(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract day of week",
    },
    DuckDbBuiltinFunction {
        name: "dayofyear",
        signature: "dayofyear(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract day of year",
    },
    DuckDbBuiltinFunction {
        name: "decade",
        signature: "decade(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract decade",
    },
    DuckDbBuiltinFunction {
        name: "degrees",
        signature: "degrees(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Radians to degrees",
    },
    DuckDbBuiltinFunction {
        name: "epoch",
        signature: "epoch(ts)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Seconds since epoch",
    },
    DuckDbBuiltinFunction {
        name: "epoch_ms",
        signature: "epoch_ms(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Milliseconds since epoch",
    },
    DuckDbBuiltinFunction {
        name: "epoch_ns",
        signature: "epoch_ns(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Nanoseconds since epoch",
    },
    DuckDbBuiltinFunction {
        name: "epoch_us",
        signature: "epoch_us(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Microseconds since epoch",
    },
    DuckDbBuiltinFunction {
        name: "error",
        signature: "error(message)",
        kind: "scalar",
        return_type: None,
        description: "Throw an error",
    },
    DuckDbBuiltinFunction {
        name: "even",
        signature: "even(x)",
        kind: "scalar",
        return_type: None,
        description: "Round away from zero to next even number",
    },
    DuckDbBuiltinFunction {
        name: "exp",
        signature: "exp(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "e raised to x",
    },
    DuckDbBuiltinFunction {
        name: "factorial",
        signature: "factorial(x)",
        kind: "scalar",
        return_type: Some("HUGEINT"),
        description: "Factorial",
    },
    DuckDbBuiltinFunction {
        name: "fdiv",
        signature: "fdiv(x, y)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Floating-point division",
    },
    DuckDbBuiltinFunction {
        name: "filter",
        signature: "filter(list, lambda)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Filter list elements",
    },
    DuckDbBuiltinFunction {
        name: "first",
        signature: "first(arg)",
        kind: "aggregate",
        return_type: None,
        description: "First value",
    },
    DuckDbBuiltinFunction {
        name: "floor",
        signature: "floor(x)",
        kind: "scalar",
        return_type: None,
        description: "Round down",
    },
    DuckDbBuiltinFunction {
        name: "format",
        signature: "format(format, ...)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Format string",
    },
    DuckDbBuiltinFunction {
        name: "from_base64",
        signature: "from_base64(string)",
        kind: "scalar",
        return_type: Some("BLOB"),
        description: "Decode base64",
    },
    DuckDbBuiltinFunction {
        name: "from_hex",
        signature: "from_hex(string)",
        kind: "scalar",
        return_type: Some("BLOB"),
        description: "Decode hexadecimal",
    },
    DuckDbBuiltinFunction {
        name: "gen_random_uuid",
        signature: "gen_random_uuid()",
        kind: "scalar",
        return_type: Some("UUID"),
        description: "Random UUID",
    },
    DuckDbBuiltinFunction {
        name: "greatest",
        signature: "greatest(arg1, arg2, ...)",
        kind: "scalar",
        return_type: None,
        description: "Greatest value",
    },
    DuckDbBuiltinFunction {
        name: "histogram",
        signature: "histogram(arg)",
        kind: "aggregate",
        return_type: Some("MAP"),
        description: "Histogram aggregate",
    },
    DuckDbBuiltinFunction {
        name: "hour",
        signature: "hour(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract hour",
    },
    DuckDbBuiltinFunction {
        name: "ifnull",
        signature: "ifnull(arg1, arg2)",
        kind: "scalar",
        return_type: None,
        description: "Return arg2 when arg1 is NULL",
    },
    DuckDbBuiltinFunction {
        name: "instr",
        signature: "instr(string, search_string)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Position of substring",
    },
    DuckDbBuiltinFunction {
        name: "isfinite",
        signature: "isfinite(x)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether value is finite",
    },
    DuckDbBuiltinFunction {
        name: "isinf",
        signature: "isinf(x)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether value is infinite",
    },
    DuckDbBuiltinFunction {
        name: "isnan",
        signature: "isnan(x)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether value is NaN",
    },
    DuckDbBuiltinFunction {
        name: "json_array",
        signature: "json_array(...)",
        kind: "scalar",
        return_type: Some("JSON"),
        description: "Create a JSON array",
    },
    DuckDbBuiltinFunction {
        name: "json_extract",
        signature: "json_extract(json, path)",
        kind: "scalar",
        return_type: Some("JSON"),
        description: "Extract JSON at path",
    },
    DuckDbBuiltinFunction {
        name: "json_extract_string",
        signature: "json_extract_string(json, path)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Extract JSON string at path",
    },
    DuckDbBuiltinFunction {
        name: "json_keys",
        signature: "json_keys(json[, path])",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "JSON object keys",
    },
    DuckDbBuiltinFunction {
        name: "json_type",
        signature: "json_type(json[, path])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "JSON value type",
    },
    DuckDbBuiltinFunction {
        name: "last",
        signature: "last(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Last value",
    },
    DuckDbBuiltinFunction {
        name: "lcase",
        signature: "lcase(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Lowercase string",
    },
    DuckDbBuiltinFunction {
        name: "least",
        signature: "least(arg1, arg2, ...)",
        kind: "scalar",
        return_type: None,
        description: "Least value",
    },
    DuckDbBuiltinFunction {
        name: "left",
        signature: "left(string, count)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Leftmost characters",
    },
    DuckDbBuiltinFunction {
        name: "len",
        signature: "len(string)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Length",
    },
    DuckDbBuiltinFunction {
        name: "length",
        signature: "length(string)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Length",
    },
    DuckDbBuiltinFunction {
        name: "levenshtein",
        signature: "levenshtein(s1, s2)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Levenshtein distance",
    },
    DuckDbBuiltinFunction {
        name: "list",
        signature: "list(arg)",
        kind: "aggregate",
        return_type: Some("LIST"),
        description: "Collect values into a list",
    },
    DuckDbBuiltinFunction {
        name: "list_aggregate",
        signature: "list_aggregate(list, function_name)",
        kind: "scalar",
        return_type: None,
        description: "Apply aggregate to list",
    },
    DuckDbBuiltinFunction {
        name: "list_append",
        signature: "list_append(list, element)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Append element to list",
    },
    DuckDbBuiltinFunction {
        name: "list_concat",
        signature: "list_concat(list1, list2)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Concatenate lists",
    },
    DuckDbBuiltinFunction {
        name: "list_contains",
        signature: "list_contains(list, element)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether list contains element",
    },
    DuckDbBuiltinFunction {
        name: "list_distinct",
        signature: "list_distinct(list)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Distinct list values",
    },
    DuckDbBuiltinFunction {
        name: "list_extract",
        signature: "list_extract(list, index)",
        kind: "scalar",
        return_type: None,
        description: "Extract list element",
    },
    DuckDbBuiltinFunction {
        name: "list_filter",
        signature: "list_filter(list, lambda)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Filter list with lambda",
    },
    DuckDbBuiltinFunction {
        name: "list_has",
        signature: "list_has(list, element)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether list has element",
    },
    DuckDbBuiltinFunction {
        name: "list_indexof",
        signature: "list_indexof(list, element)",
        kind: "scalar",
        return_type: Some("INTEGER"),
        description: "Index of element in list",
    },
    DuckDbBuiltinFunction {
        name: "list_pack",
        signature: "list_pack(arg1, arg2, ...)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Create a list",
    },
    DuckDbBuiltinFunction {
        name: "list_position",
        signature: "list_position(list, element)",
        kind: "scalar",
        return_type: Some("INTEGER"),
        description: "Position of element in list",
    },
    DuckDbBuiltinFunction {
        name: "list_resize",
        signature: "list_resize(list, size[, value])",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Resize list",
    },
    DuckDbBuiltinFunction {
        name: "list_reverse_sort",
        signature: "list_reverse_sort(list)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Sort list descending",
    },
    DuckDbBuiltinFunction {
        name: "list_slice",
        signature: "list_slice(list, begin, end)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Slice list",
    },
    DuckDbBuiltinFunction {
        name: "list_sort",
        signature: "list_sort(list)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Sort list",
    },
    DuckDbBuiltinFunction {
        name: "list_transform",
        signature: "list_transform(list, lambda)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Transform list with lambda",
    },
    DuckDbBuiltinFunction {
        name: "list_unique",
        signature: "list_unique(list)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Number of unique list values",
    },
    DuckDbBuiltinFunction {
        name: "ln",
        signature: "ln(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Natural logarithm",
    },
    DuckDbBuiltinFunction {
        name: "log",
        signature: "log(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Base-10 logarithm",
    },
    DuckDbBuiltinFunction {
        name: "log10",
        signature: "log10(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Base-10 logarithm",
    },
    DuckDbBuiltinFunction {
        name: "log2",
        signature: "log2(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Base-2 logarithm",
    },
    DuckDbBuiltinFunction {
        name: "lower",
        signature: "lower(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Converts string to lower case",
    },
    DuckDbBuiltinFunction {
        name: "lpad",
        signature: "lpad(string, count[, character])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Pad string on the left",
    },
    DuckDbBuiltinFunction {
        name: "ltrim",
        signature: "ltrim(string[, characters])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Trim characters from left side",
    },
    DuckDbBuiltinFunction {
        name: "make_date",
        signature: "make_date(year, month, day)",
        kind: "scalar",
        return_type: Some("DATE"),
        description: "Construct a date",
    },
    DuckDbBuiltinFunction {
        name: "make_time",
        signature: "make_time(hour, minute, second)",
        kind: "scalar",
        return_type: Some("TIME"),
        description: "Construct a time",
    },
    DuckDbBuiltinFunction {
        name: "make_timestamp",
        signature: "make_timestamp(year, month, day, hour, minute, second)",
        kind: "scalar",
        return_type: Some("TIMESTAMP"),
        description: "Construct a timestamp",
    },
    DuckDbBuiltinFunction {
        name: "max",
        signature: "max(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Maximum value",
    },
    DuckDbBuiltinFunction {
        name: "md5",
        signature: "md5(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "MD5 hash",
    },
    DuckDbBuiltinFunction {
        name: "mean",
        signature: "mean(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Average value",
    },
    DuckDbBuiltinFunction {
        name: "median",
        signature: "median(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Median value",
    },
    DuckDbBuiltinFunction {
        name: "microsecond",
        signature: "microsecond(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract microsecond",
    },
    DuckDbBuiltinFunction {
        name: "millisecond",
        signature: "millisecond(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract millisecond",
    },
    DuckDbBuiltinFunction {
        name: "min",
        signature: "min(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Minimum value",
    },
    DuckDbBuiltinFunction {
        name: "minute",
        signature: "minute(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract minute",
    },
    DuckDbBuiltinFunction {
        name: "mode",
        signature: "mode(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Most frequent value",
    },
    DuckDbBuiltinFunction {
        name: "month",
        signature: "month(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract month",
    },
    DuckDbBuiltinFunction {
        name: "monthname",
        signature: "monthname(date)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Month name",
    },
    DuckDbBuiltinFunction {
        name: "nextafter",
        signature: "nextafter(x, y)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Next representable value",
    },
    DuckDbBuiltinFunction {
        name: "now",
        signature: "now()",
        kind: "scalar",
        return_type: Some("TIMESTAMP WITH TIME ZONE"),
        description: "Current timestamp",
    },
    DuckDbBuiltinFunction {
        name: "nullif",
        signature: "nullif(a, b)",
        kind: "scalar",
        return_type: None,
        description: "NULL if arguments are equal",
    },
    DuckDbBuiltinFunction {
        name: "parse_dirname",
        signature: "parse_dirname(path)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Directory name from path",
    },
    DuckDbBuiltinFunction {
        name: "parse_dirpath",
        signature: "parse_dirpath(path)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Directory path from path",
    },
    DuckDbBuiltinFunction {
        name: "parse_filename",
        signature: "parse_filename(path)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "File name from path",
    },
    DuckDbBuiltinFunction {
        name: "pi",
        signature: "pi()",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Pi constant",
    },
    DuckDbBuiltinFunction {
        name: "pow",
        signature: "pow(x, y)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Power",
    },
    DuckDbBuiltinFunction {
        name: "power",
        signature: "power(x, y)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Power",
    },
    DuckDbBuiltinFunction {
        name: "prefix",
        signature: "prefix(string, search_string)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether string starts with search string",
    },
    DuckDbBuiltinFunction {
        name: "printf",
        signature: "printf(format, ...)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Printf-style format",
    },
    DuckDbBuiltinFunction {
        name: "product",
        signature: "product(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Product aggregate",
    },
    DuckDbBuiltinFunction {
        name: "quantile_cont",
        signature: "quantile_cont(x, pos)",
        kind: "aggregate",
        return_type: None,
        description: "Continuous quantile",
    },
    DuckDbBuiltinFunction {
        name: "quantile_disc",
        signature: "quantile_disc(x, pos)",
        kind: "aggregate",
        return_type: None,
        description: "Discrete quantile",
    },
    DuckDbBuiltinFunction {
        name: "radians",
        signature: "radians(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Degrees to radians",
    },
    DuckDbBuiltinFunction {
        name: "random",
        signature: "random()",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Random value in [0, 1)",
    },
    DuckDbBuiltinFunction {
        name: "range",
        signature: "range([start,] stop[, step])",
        kind: "table",
        return_type: Some("TABLE"),
        description: "Generate a range",
    },
    DuckDbBuiltinFunction {
        name: "regexp_escape",
        signature: "regexp_escape(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Escape regular expression characters",
    },
    DuckDbBuiltinFunction {
        name: "regexp_extract",
        signature: "regexp_extract(string, regex[, group])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Extract regex group",
    },
    DuckDbBuiltinFunction {
        name: "regexp_extract_all",
        signature: "regexp_extract_all(string, regex[, group])",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Extract all regex matches",
    },
    DuckDbBuiltinFunction {
        name: "regexp_full_match",
        signature: "regexp_full_match(string, regex)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether regex fully matches",
    },
    DuckDbBuiltinFunction {
        name: "regexp_matches",
        signature: "regexp_matches(string, regex)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether regex matches",
    },
    DuckDbBuiltinFunction {
        name: "regexp_replace",
        signature: "regexp_replace(string, regex, replacement)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Replace regex match",
    },
    DuckDbBuiltinFunction {
        name: "repeat",
        signature: "repeat(string, count)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Repeat string",
    },
    DuckDbBuiltinFunction {
        name: "replace",
        signature: "replace(string, source, target)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Replace substring",
    },
    DuckDbBuiltinFunction {
        name: "reverse",
        signature: "reverse(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Reverse string",
    },
    DuckDbBuiltinFunction {
        name: "right",
        signature: "right(string, count)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Rightmost characters",
    },
    DuckDbBuiltinFunction {
        name: "round",
        signature: "round(x[, s])",
        kind: "scalar",
        return_type: None,
        description: "Round number",
    },
    DuckDbBuiltinFunction {
        name: "row_to_json",
        signature: "row_to_json(row)",
        kind: "scalar",
        return_type: Some("JSON"),
        description: "Convert row to JSON",
    },
    DuckDbBuiltinFunction {
        name: "rpad",
        signature: "rpad(string, count[, character])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Pad string on the right",
    },
    DuckDbBuiltinFunction {
        name: "rtrim",
        signature: "rtrim(string[, characters])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Trim characters from right side",
    },
    DuckDbBuiltinFunction {
        name: "second",
        signature: "second(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract second",
    },
    DuckDbBuiltinFunction {
        name: "sha1",
        signature: "sha1(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "SHA1 hash",
    },
    DuckDbBuiltinFunction {
        name: "sha256",
        signature: "sha256(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "SHA256 hash",
    },
    DuckDbBuiltinFunction {
        name: "sign",
        signature: "sign(x)",
        kind: "scalar",
        return_type: None,
        description: "Sign of number",
    },
    DuckDbBuiltinFunction {
        name: "sin",
        signature: "sin(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Sine",
    },
    DuckDbBuiltinFunction {
        name: "sinh",
        signature: "sinh(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Hyperbolic sine",
    },
    DuckDbBuiltinFunction {
        name: "sqrt",
        signature: "sqrt(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Square root",
    },
    DuckDbBuiltinFunction {
        name: "starts_with",
        signature: "starts_with(string, search_string)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether string starts with search string",
    },
    DuckDbBuiltinFunction {
        name: "stats",
        signature: "stats(expr)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Statistics for expression",
    },
    DuckDbBuiltinFunction {
        name: "str_split",
        signature: "str_split(string, separator)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Split string",
    },
    DuckDbBuiltinFunction {
        name: "strftime",
        signature: "strftime(date, format)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Format date/time",
    },
    DuckDbBuiltinFunction {
        name: "string_agg",
        signature: "string_agg(arg[, sep])",
        kind: "aggregate",
        return_type: Some("VARCHAR"),
        description: "Concatenate aggregate",
    },
    DuckDbBuiltinFunction {
        name: "string_split",
        signature: "string_split(string, separator)",
        kind: "scalar",
        return_type: Some("LIST"),
        description: "Split string",
    },
    DuckDbBuiltinFunction {
        name: "strip_accents",
        signature: "strip_accents(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Strip accents",
    },
    DuckDbBuiltinFunction {
        name: "strpos",
        signature: "strpos(string, search_string)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Position of substring",
    },
    DuckDbBuiltinFunction {
        name: "strptime",
        signature: "strptime(text, format)",
        kind: "scalar",
        return_type: Some("TIMESTAMP"),
        description: "Parse timestamp",
    },
    DuckDbBuiltinFunction {
        name: "substr",
        signature: "substr(string, start[, length])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Substring",
    },
    DuckDbBuiltinFunction {
        name: "substring",
        signature: "substring(string, start[, length])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Substring",
    },
    DuckDbBuiltinFunction {
        name: "suffix",
        signature: "suffix(string, search_string)",
        kind: "scalar",
        return_type: Some("BOOLEAN"),
        description: "Whether string ends with search string",
    },
    DuckDbBuiltinFunction {
        name: "sum",
        signature: "sum(arg)",
        kind: "aggregate",
        return_type: None,
        description: "Sum aggregate",
    },
    DuckDbBuiltinFunction {
        name: "tan",
        signature: "tan(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Tangent",
    },
    DuckDbBuiltinFunction {
        name: "tanh",
        signature: "tanh(x)",
        kind: "scalar",
        return_type: Some("DOUBLE"),
        description: "Hyperbolic tangent",
    },
    DuckDbBuiltinFunction {
        name: "time_bucket",
        signature: "time_bucket(bucket_width, timestamp[, origin])",
        kind: "scalar",
        return_type: None,
        description: "Truncate timestamp to time bucket",
    },
    DuckDbBuiltinFunction {
        name: "timezone",
        signature: "timezone(zone, timestamp)",
        kind: "scalar",
        return_type: None,
        description: "Convert or extract timezone",
    },
    DuckDbBuiltinFunction {
        name: "to_base",
        signature: "to_base(number, radix[, min_length])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Convert number to base",
    },
    DuckDbBuiltinFunction {
        name: "to_base64",
        signature: "to_base64(blob)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Base64 encode blob",
    },
    DuckDbBuiltinFunction {
        name: "to_binary",
        signature: "to_binary(value)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Binary representation",
    },
    DuckDbBuiltinFunction {
        name: "to_days",
        signature: "to_days(integer)",
        kind: "scalar",
        return_type: Some("INTERVAL"),
        description: "Construct day interval",
    },
    DuckDbBuiltinFunction {
        name: "to_hex",
        signature: "to_hex(value)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Hexadecimal representation",
    },
    DuckDbBuiltinFunction {
        name: "to_json",
        signature: "to_json(value)",
        kind: "scalar",
        return_type: Some("JSON"),
        description: "Convert value to JSON",
    },
    DuckDbBuiltinFunction {
        name: "to_months",
        signature: "to_months(integer)",
        kind: "scalar",
        return_type: Some("INTERVAL"),
        description: "Construct month interval",
    },
    DuckDbBuiltinFunction {
        name: "to_seconds",
        signature: "to_seconds(double)",
        kind: "scalar",
        return_type: Some("INTERVAL"),
        description: "Construct second interval",
    },
    DuckDbBuiltinFunction {
        name: "to_timestamp",
        signature: "to_timestamp(sec)",
        kind: "scalar",
        return_type: Some("TIMESTAMP WITH TIME ZONE"),
        description: "Seconds since epoch to timestamp",
    },
    DuckDbBuiltinFunction {
        name: "translate",
        signature: "translate(string, from, to)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Translate characters",
    },
    DuckDbBuiltinFunction {
        name: "trim",
        signature: "trim(string[, characters])",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Trim characters",
    },
    DuckDbBuiltinFunction {
        name: "trunc",
        signature: "trunc(x[, s])",
        kind: "scalar",
        return_type: None,
        description: "Truncate number",
    },
    DuckDbBuiltinFunction {
        name: "try_strptime",
        signature: "try_strptime(text, format)",
        kind: "scalar",
        return_type: Some("TIMESTAMP"),
        description: "Parse timestamp, returning NULL on failure",
    },
    DuckDbBuiltinFunction {
        name: "typeof",
        signature: "typeof(expression)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Type name of expression",
    },
    DuckDbBuiltinFunction {
        name: "ucase",
        signature: "ucase(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Uppercase string",
    },
    DuckDbBuiltinFunction {
        name: "unhex",
        signature: "unhex(value)",
        kind: "scalar",
        return_type: Some("BLOB"),
        description: "Decode hexadecimal",
    },
    DuckDbBuiltinFunction {
        name: "unicode",
        signature: "unicode(string)",
        kind: "scalar",
        return_type: Some("INTEGER"),
        description: "Unicode codepoint",
    },
    DuckDbBuiltinFunction {
        name: "unnest",
        signature: "unnest(list)",
        kind: "table",
        return_type: Some("TABLE"),
        description: "Unnest a list",
    },
    DuckDbBuiltinFunction {
        name: "upper",
        signature: "upper(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Converts string to upper case",
    },
    DuckDbBuiltinFunction {
        name: "url_decode",
        signature: "url_decode(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Decode URL percent encoding",
    },
    DuckDbBuiltinFunction {
        name: "url_encode",
        signature: "url_encode(string)",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "Encode URL percent encoding",
    },
    DuckDbBuiltinFunction {
        name: "uuid",
        signature: "uuid()",
        kind: "scalar",
        return_type: Some("UUID"),
        description: "Random UUID v4",
    },
    DuckDbBuiltinFunction {
        name: "uuidv4",
        signature: "uuidv4()",
        kind: "scalar",
        return_type: Some("UUID"),
        description: "Random UUID v4",
    },
    DuckDbBuiltinFunction {
        name: "uuidv7",
        signature: "uuidv7()",
        kind: "scalar",
        return_type: Some("UUID"),
        description: "Random UUID v7",
    },
    DuckDbBuiltinFunction {
        name: "var_pop",
        signature: "var_pop(x)",
        kind: "aggregate",
        return_type: Some("DOUBLE"),
        description: "Population variance",
    },
    DuckDbBuiltinFunction {
        name: "var_samp",
        signature: "var_samp(x)",
        kind: "aggregate",
        return_type: Some("DOUBLE"),
        description: "Sample variance",
    },
    DuckDbBuiltinFunction {
        name: "variance",
        signature: "variance(x)",
        kind: "aggregate",
        return_type: Some("DOUBLE"),
        description: "Sample variance",
    },
    DuckDbBuiltinFunction {
        name: "version",
        signature: "version()",
        kind: "scalar",
        return_type: Some("VARCHAR"),
        description: "DuckDB version",
    },
    DuckDbBuiltinFunction {
        name: "week",
        signature: "week(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract week",
    },
    DuckDbBuiltinFunction {
        name: "weekday",
        signature: "weekday(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract weekday",
    },
    DuckDbBuiltinFunction {
        name: "year",
        signature: "year(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract year",
    },
    DuckDbBuiltinFunction {
        name: "yearweek",
        signature: "yearweek(ts)",
        kind: "scalar",
        return_type: Some("BIGINT"),
        description: "Extract year-week",
    },
];
